### PR TITLE
Jb access duration changes

### PR DESCRIPTION
**Pull request by Jui1337**
This PR is for the changes made for the ticket - PLATSEC-2946: As a Discord Access Administrator ISBAT configure the default access durations time as well the available ones. The access time duration for the roles being created or added are now been converted into environment variables to make it easier for maintaining default values for discord-access public repo, and still have our own modifications if need be.

### CODE REVIEW

**Comment by jonathanhle** [comment]
@Jui1337 click "Ready for review" when you're ready for a review too

**Comment by jonathanhle** [comment]
> @Jui1337 click "Ready for review" when you're ready for a review too

I clicked "Ready for review" for you this time :-)

**Comment by jonathanhle** [comment]
I don't really write any React to know what's appropriate of if this answers the ticket.  Let's step through on your local env tomorrow.

**Comment by Jui1337** [comment]
@jonathanhle ready to be merged, requesting for final review.

**Review by jonathanhle — APPROVED** [review]
LGTM

**Pull request merged**
